# Generated by Django 4.2.3 on 2024-11-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=400)),
                ('phone_number', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10)),
                ('role', models.CharField(choices=[(1, 'Admin'), (2, 'Pharmacist'), (3, 'Client')], max_length=10)),
            ],
        ),
    ]
