# Generated by Django 4.2.3 on 2024-12-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='profile_images/default_profile.png', upload_to=users.models.user_directory_path)),
                ('address', models.CharField(max_length=400)),
                ('phone_number', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Pharmacist'), (3, 'Client')], default=3)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
