# Generated by Django 4.2.3 on 2025-01-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[(0, 'Rejected'), (1, 'Pending'), (2, 'Under Approval'), (3, 'Approved And Received'), (4, 'Requested'), (5, 'Donation Sent')], default=1, max_length=30),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donations/')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
