# Generated by Django 4.2.3 on 2025-01-06 22:10

from django.db import migrations, models
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_status_donationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=donations.models.upload_to_requested),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[(0, 'Rejected'), (1, 'Pending'), (2, 'Approved'), (3, 'Donation Sent')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(upload_to=donations.models.upload_to_donated),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[(0, 'Rejected'), (1, 'Pending'), (2, 'Approved'), (3, 'Requested'), (4, 'Donation Sent')], default=1, max_length=30),
        ),
    ]
