# Generated by Django 4.2.3 on 2025-01-06 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0003_remove_donationrequest_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('0', 'Rejected'), ('1', 'Pending'), ('2', 'Approved'), ('3', 'Requested'), ('4', 'Donation Sent')], default=1, max_length=30),
        ),
    ]
