# Generated by Django 4.2.3 on 2025-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_donationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Pending'), (2, 'Approved'), (3, 'Sent')], default=1),
        ),
    ]
