# Generated by Django 4.2.3 on 2024-11-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_order_created_by_remove_order_dispensed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_no', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugId', to='products.drug')),
            ],
        ),
    ]
