# Generated by Django 4.2.3 on 2024-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='price',
            new_name='pharmacist_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='public_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
