# Generated by Django 4.2.3 on 2024-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_inventoryitem_pharmacist_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
