# Generated by Django 4.2.3 on 2024-12-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_drug_img'),
        ('inventory', '0003_alter_inventoryitem_id'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='drug_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.drug'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='inventory_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
    ]
