# Generated by Django 4.2.3 on 2024-12-07 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_inventoryitem_id'),
        ('orders', '0003_alter_order_dispensed_by_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispensed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Under Delivery'), (3, 'Done')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='inventory_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
    ]
