# Generated by Django 4.2.17 on 2024-12-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitemdispensed'),
        ('orders', '0004_remove_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='inventory_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitemdispensed'),
        ),
    ]
