# Generated by Django 4.2.3 on 2024-12-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_dispensed_by_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='drug_id',
            field=models.IntegerField(),
        ),
    ]
