# Generated by Django 4.2.3 on 2024-12-08 17:50

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('active_ingrendients', models.CharField(default='', max_length=5000)),
                ('price', models.CharField(default='', max_length=500)),
                ('company', models.CharField(default='', max_length=1000)),
                ('group', models.CharField(default='', max_length=1000)),
                ('data', models.TextField(default='')),
                ('route', models.CharField(default='', max_length=1000)),
                ('img', models.FileField(default='drug_pics/drug_default.png', upload_to=products.models.upload_directory)),
            ],
        ),
    ]
