# Generated by Django 4.2.3 on 2024-11-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='inventory_id_id',
            new_name='inventory_id',
        ),
    ]
