# Generated by Django 4.2.3 on 2024-11-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_inventory_id_id_orderitem_inventory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='contradiction',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='indication',
        ),
        migrations.AddField(
            model_name='drug',
            name='active_ingrendients',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='drug',
            name='company',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='drug',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='drug',
            name='group',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='drug',
            name='route',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
