# Generated by Django 4.2.3 on 2024-11-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_drug_contradiction_remove_drug_indication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
