# Generated by Django 4.2.17 on 2024-12-05 17:26

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_created_by_remove_order_dispensed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='img',
            field=models.FileField(default='drug_default.png', upload_to=products.models.user_directory_path),
        ),
    ]
